from flask import Blueprint, request, jsonify
from datetime import datetime, timedelta
import secrets
import string
import random
from firebase_admin import auth as firebase_auth
from app.middleware.auth import verify_token, require_role
from app.services.firestore_service import (
    create_student, list_students, delete_student, 
    list_users_by_role, delete_user_record,
    get_attendance, mark_attendance, create_user,
    list_courses, add_mark, update_student
)

admin_bp = Blueprint("admin", __name__)

@admin_bp.route("/get-students", methods=["GET"])
@admin_bp.route("/students", methods=["GET"])
@verify_token
@require_role("admin")
def get_all_students():
    students = list_students()
    return jsonify(students), 200

@admin_bp.route("/add-student", methods=["POST"])
@verify_token
@require_role("admin")
def add_student():
    data = request.json
    email = data.get("email")
    name = data.get("name")
    course = data.get("course") # Display Name
    course_id = data.get("courseId") # Internal ID
    semester = data.get("semester", 1) # Current Semester
    password = data.get("password")
    faculty_assigned = data.get("facultyAssigned", "Not Assigned")

    if not email or not name:
        return jsonify({"error": "Email and Name are required"}), 400

    # Auto-generate password if not provided
    is_auto_generated = False
    if not password:
        is_auto_generated = True
        alphabet = string.ascii_letters + string.digits + "!@#$%&*?"
        password = ''.join(secrets.choice(alphabet) for i in range(12))

    try:
        # 1. Create User in Firebase Auth automatically
        user_record = firebase_auth.create_user(
            email=email,
            display_name=name,
            password=password,
        )
        uid = user_record.uid

        # 2. Create User Role in Firestore (collection: users)
        create_user(uid, {
            "uid": uid,
            "name": name,
            "email": email,
            "role": "student",
            "courseId": course_id,
            "semester": int(semester)
        })

        # 3. Create Student Profile in Firestore (collection: students)
        student_profile = create_student(uid, {
            "uid": uid,
            "name": name,
            "email": email,
            "course": course,
            "courseId": course_id,
            "semester": int(semester),
            "facultyAssigned": faculty_assigned,
            "feesPaid": False
        })

        return jsonify({
            "message": "Student created successfully",
            "uid": uid,
            "email": email,
            "password": password,
            "isAutoGenerated": is_auto_generated
        }), 201

    except Exception as e:
        print(f"FAILED TO CREATE STUDENT: {str(e)}")
        return jsonify({"error": f"Failed to create student: {str(e)}"}), 500

@admin_bp.route("/update-student", methods=["PUT"])
@verify_token
@require_role("admin")
def edit_student():
    data = request.json
    uid = data.get("uid")
    if not uid: return jsonify({"error": "uid is required"}), 400
    
    try:
        # 1. Update Firebase Auth if email/name/password changed
        auth_updates = {}
        if data.get("email"): auth_updates["email"] = data["email"]
        if data.get("name"): auth_updates["display_name"] = data["name"]
        if data.get("password"): auth_updates["password"] = data["password"]
        
        if auth_updates:
            firebase_auth.update_user(uid, **auth_updates)
            
        # 2. Update Firestore (users collection)
        user_updates = {
            "name": data.get("name"),
            "email": data.get("email"),
            "courseId": data.get("courseId"),
            "semester": int(data.get("semester")) if data.get("semester") else None,
            "role": "student"
        }
        user_updates = {k: v for k, v in user_updates.items() if v is not None}
        create_user(uid, user_updates)
        
        # 3. Update Firestore (students collection)
        student_updates = {
            "name": data.get("name"),
            "email": data.get("email"),
            "course": data.get("course"),
            "courseId": data.get("courseId"),
            "semester": int(data.get("semester")) if data.get("semester") else None,
            "facultyAssigned": data.get("facultyAssigned"),
            "totalFees": float(data.get("totalFees")) if data.get("totalFees") is not None else None,
            "pendingAmount": float(data.get("pendingAmount")) if data.get("pendingAmount") is not None else None
        }
        student_updates = {k: v for k, v in student_updates.items() if v is not None}
        update_student(uid, student_updates)
        
        return jsonify({"message": "Student profile synchronized successfully"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@admin_bp.route("/delete-student", methods=["DELETE"])
@verify_token
@require_role("admin")
def remove_student():
    student_id = request.args.get("studentId")
    if not student_id:
        return jsonify({"error": "studentId query parameter is required"}), 400
        
    try:
        # 1. Delete Firestore records in both collections
        delete_student(student_id)
        
        # 2. Delete from Firebase Auth
        try:
            firebase_auth.delete_user(student_id)
        except Exception as auth_err:
            print(f"Warning: Auth user not found while deleting record: {str(auth_err)}")
        
        return jsonify({"message": "Student deleted successfully from all systems"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@admin_bp.route("/add-faculty", methods=["POST"])
@verify_token
@require_role("admin")
def add_faculty():
    data = request.json
    email = data.get("email")
    name = data.get("name")
    department = data.get("department", "General")
    assigned_courses = data.get("assignedCourses", [])
    assigned_subjects = data.get("assignedSubjects", [])
    assigned_semesters = data.get("assignedSemesters", [])
    password = data.get("password")

    if not email or not name:
        return jsonify({"error": "Email and Name are required"}), 400

    if not password:
        alphabet = string.ascii_letters + string.digits + "!@#$%&*?"
        password = ''.join(secrets.choice(alphabet) for i in range(12))

    try:
        # 1. Create Auth User
        user_record = firebase_auth.create_user(
            email=email,
            display_name=name,
            password=password
        )
        uid = user_record.uid

        # 2. Store in Firestore (users collection)
        create_user(uid, {
            "uid": uid,
            "name": name,
            "email": email,
            "role": "faculty",
            "department": department,
            "assignedCourses": assigned_courses,
            "assignedSubjects": assigned_subjects,
            "assignedSemesters": [int(x) for x in assigned_semesters] if assigned_semesters else []
        })

        return jsonify({
            "message": "Faculty account created",
            "uid": uid,
            "email": email,
            "password": password
        }), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@admin_bp.route("/update-faculty", methods=["PUT"])
@verify_token
@require_role("admin")
def edit_faculty():
    data = request.json
    uid = data.get("uid")
    if not uid: return jsonify({"error": "uid is required"}), 400
    
    try:
        # 1. Auth updates
        auth_updates = {}
        if data.get("email"): auth_updates["email"] = data["email"]
        if data.get("name"): auth_updates["display_name"] = data["name"]
        if data.get("password"): auth_updates["password"] = data["password"]
        
        if auth_updates:
            firebase_auth.update_user(uid, **auth_updates)
            
        # 2. Firestore updates
        faculty_updates = {
            "name": data.get("name"),
            "email": data.get("email"),
            "department": data.get("department"),
            "assignedCourses": data.get("assignedCourses"),
            "assignedSubjects": data.get("assignedSubjects"),
            "assignedSemesters": [int(x) for x in data.get("assignedSemesters")] if data.get("assignedSemesters") is not None else None,
            "role": "faculty"
        }
        faculty_updates = {k: v for k, v in faculty_updates.items() if v is not None}
        create_user(uid, faculty_updates)
        
        return jsonify({"message": "Faculty account synchronized successfully"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@admin_bp.route("/delete-faculty", methods=["DELETE"])
@verify_token
@require_role("admin")
def remove_faculty():
    faculty_id = request.args.get("facultyId")
    if not faculty_id:
        return jsonify({"error": "facultyId query parameter is required"}), 400
        
    try:
        # 1. Delete from Firestore users collection
        delete_user_record(faculty_id)
        
        # 2. Delete from Firebase Auth
        try:
            firebase_auth.delete_user(faculty_id)
        except Exception as auth_err:
            print(f"Warning: Faculty auth user not found while deleting record: {str(auth_err)}")
        
        return jsonify({"message": "Faculty account successfully purged from institutional registry"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@admin_bp.route("/get-faculty", methods=["GET"])
@admin_bp.route("/faculty", methods=["GET"])
@verify_token
@require_role("admin")
def get_all_faculty():
    faculty = list_users_by_role("faculty")
    return jsonify(faculty), 200

@admin_bp.route("/stats", methods=["GET"])
@verify_token
@require_role("admin")
def get_stats():
    # Advanced stats for admin dashboard
    students = list_students()
    faculty = list_users_by_role("faculty")
    
    total_revenue = 0
    total_pending = 0
    collections_by_mode = {}
    
    for s in students:
        total = float(s.get("totalFees", 0))
        pending = float(s.get("pendingAmount", 0))
        paid = total - pending
        
        total_revenue += paid
        total_pending += pending
    
    return jsonify({
        "totalStudents": len(students),
        "totalFaculty": len(faculty),
        "totalRevenue": total_revenue,
        "totalPending": total_pending,
        "roleDistribution": {
            "students": len(students),
            "faculty": len(faculty)
        }
    }), 200

@admin_bp.route("/get-attendance", methods=["GET"])
@verify_token
@require_role("admin")
def admin_get_attendance():
    student_id = request.args.get("studentId")
    if not student_id:
        return jsonify({"error": "studentId is required"}), 400
    records = get_attendance(student_id)
    return jsonify(records), 200

@admin_bp.route("/mark-attendance", methods=["POST"])
@verify_token
@require_role("admin")
def admin_mark_attendance():
    data = request.json
    student_id = data.get("studentId")
    status = data.get("status")
    date = data.get("date")
    subject = data.get("subject", "General")
    
    if not student_id or not status or not date:
        return jsonify({"error": "studentId, status, and date are required"}), 400
        
    record = {
        "date": date,
        "subject": subject,
        "status": status,
        "markedBy": "admin",
        "teacherName": "Admin System",
        "timestamp": datetime.now().isoformat()
    }
    
    result = mark_attendance(student_id, record)
    return jsonify(result), 200

@admin_bp.route("/seed-data", methods=["POST"])
@verify_token
@require_role("admin")
def seed_data():
    """
    Populates Firestore and Auth with mock data if not exists.
    Users created with password: 'Password123'
    """
    created_users = []
    
    courses = list_courses()
    bca = next((c for c in courses if c["courseName"] == "BCA"), None)
    bba = next((c for c in courses if c["courseName"] == "BBA"), None)

    # ── 1. Mock Faculty Data ──────────────────────────────────────────────────
    faculty_data = [
        {"name": "Prof. Alan Turing", "email": "turing@acadex.edu", "dept": "Computer Science", "courses": [bca["id"]] if bca else []},
        {"name": "Prof. Grace Hopper", "email": "hopper@acadex.edu", "dept": "Mathematics", "courses": [bba["id"]] if bba else []}
    ]
    
    faculty_ids = []
    for f in faculty_data:
        try:
            # Check if exists in Auth
            try:
                user = firebase_auth.get_user_by_email(f["email"])
                uid = user.uid
            except:
                user = firebase_auth.create_user(email=f["email"], display_name=f["name"], password="Password123")
                uid = user.uid
            
            create_user(uid, {
                "uid": uid, "name": f["name"], "email": f["email"], "role": "faculty", 
                "department": f["dept"], "assignedCourses": f["courses"], "assignedSemesters": [1, 2, 3]
            })
            faculty_ids.append(uid)
            created_users.append(f["email"])
        except Exception as e: print(f"Seed Faculty Error: {str(e)}")

    # ── 2. Mock Student Data ──────────────────────────────────────────────────
    student_data = [
        {"name": "Alice Wong", "email": "alice@acadex.edu", "course": "BCA", "courseId": bca["id"] if bca else "N/A"},
        {"name": "Bob Martin", "email": "bob@acadex.edu", "course": "BCA", "courseId": bca["id"] if bca else "N/A"},
        {"name": "Charlie Brown", "email": "charlie@acadex.edu", "course": "BBA", "courseId": bba["id"] if bba else "N/A"},
        {"name": "Dana Scully", "email": "dana@acadex.edu", "course": "BBA", "courseId": bba["id"] if bba else "N/A"},
        {"name": "Fox Mulder", "email": "fox@acadex.edu", "course": "BCA", "courseId": bca["id"] if bca else "N/A"}
    ]

    subjects = ["Mathematics", "Computer Science", "Physics", "English"]
    
    for i, s in enumerate(student_data):
        try:
            # Check Auth
            try:
                user = firebase_auth.get_user_by_email(s["email"])
                uid = user.uid
            except:
                user = firebase_auth.create_user(email=s["email"], display_name=s["name"], password="Password123")
                uid = user.uid
            
            # Assign faculty based on course
            assigned_f = faculty_ids[0] if "CS" in s["course"] else faculty_ids[1]
            
            # Update Firestore
            create_user(uid, {
                "uid": uid, "name": s["name"], "email": s["email"], "role": "student",
                "courseId": s["courseId"], "semester": 1
            })
            create_student(uid, {
                "uid": uid, "name": s["name"], "email": s["email"], 
                "course": s["course"], "courseId": s["courseId"], "semester": 1,
                "facultyAssigned": assigned_f, "feesPaid": False,
                "totalFees": 80000 if "BCA" in s["course"] else 50000,
                "pendingAmount": 80000 if "BCA" in s["course"] else 50000
            })
            
            # ── 3. Seed Attendance & Marks (Subcollections) ───────────────────
            for sub in subjects:
                # Add 3 days of attendance
                for d in range(3):
                    date_str = (datetime.now() - timedelta(days=d)).strftime("%Y-%m-%d")
                    mark_attendance(uid, {
                        "date": date_str,
                        "subject": sub,
                        "status": random.choice(["present", "present", "absent"]), # Weighted
                        "markedBy": assigned_f,
                        "teacherName": "Seeded Content",
                        "timestamp": datetime.now().isoformat()
                    })
            
            created_users.append(s["email"])
        except Exception as e: print(f"Seed Student Error: {str(e)}")

    return jsonify({
        "message": "Seeding completed successfully",
        "users_checked": created_users,
        "default_password": "Password123"
    }), 200


@admin_bp.route("/seed/marks", methods=["POST"])
@verify_token
@require_role("admin")
def seed_marks():
    students = list_students()
    faculty = list_users_by_role("faculty")
    
    if not students or not faculty:
        return jsonify({"error": "No students or faculty found to seed marks for."}), 400

    faculty_ids = [f["uid"] for f in faculty]
    faculty_names = [f["name"] for f in faculty]

    subjects = ["Mathematics", "Computer Science", "Physics", "English", "Chemistry"]
    exam_types = ["Midterm", "Final", "Assignment 1", "Assignment 2", "Project"]
    
    marks_added = 0
    errors = 0

    for student in students:
        sid = student.get("uid") or student.get("id")
        if not sid: continue
        
        # Pick 3-5 random subjects to avoid too many entries
        student_subjects = random.sample(subjects, random.randint(3, 5))
        
        for subject in student_subjects:
            for exam_type in exam_types:
                # 80% chance they took this exam type to add realism
                if random.random() < 0.8:
                    teacher_idx = random.randint(0, len(faculty)-1)
                    teacher_uid = faculty_ids[teacher_idx]
                    teacher_name = faculty_names[teacher_idx]
                    
                    date_str = (datetime.now() - timedelta(days=random.randint(1, 60))).strftime("%Y-%m-%d")
                    
                    # Score between 50 and 95
                    score = random.randint(50, 95)
                    max_marks = 100 if exam_type in ["Midterm", "Final"] else random.choice([20, 50, 100])
                    if max_marks < 100:
                        score = int((score / 100) * max_marks)
                    
                    try:
                        add_mark(sid, {
                            "subject": subject,
                            "examType": exam_type,
                            "score": float(score),
                            "maxMarks": float(max_marks),
                            "date": date_str,
                            "markedBy": teacher_uid,
                            "teacherName": teacher_name,
                            "createdAt": datetime.now().isoformat(),
                            "lastUpdatedAt": datetime.now().isoformat()
                        })
                        marks_added += 1
                    except Exception as e:
                        # Ignore duplicates or validation errors from add_mark
                        errors += 1

    return jsonify({
        "message": "Marks seeded successfully.",
        "records_added": marks_added,
        "errors_skipped": errors
    }), 200
